tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.index, name="home"),
    path("<str:slug>/update", views.update, name="update"),
    path("<str:slug>/delete", views.delete, name="delete"),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("tasks.urls", namespace="index")),
    path("admin/", admin.site.urls),
]

tasks/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.


class Task(models.Model):
    title = models.CharField(max_length=500)
    slug = models.SlugField(unique=True, editable=False)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

tasks/forms.py
from django import forms
from .models import Task


class TaskFrom(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "title",
            "completed",
        ]

tasks/views.py
from django.shortcuts import render, redirect

from .models import Task
from .forms import TaskFrom

# Create your views here.


def index(request):
    tasks = Task.objects.all()

    if request.method == "POST":
        form = TaskFrom(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = TaskFrom()

    context = {
        "tasks": tasks,
        "form": form,
    }
    return render(request, "list.html", context)


def update(request, slug):
    task = Task.objects.get(slug=slug)

    if request.method == "POST":
        form = TaskFrom(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = TaskFrom(instance=task)

    context = {
        "task": task,
        "form": form,
    }
    return render(request, "update.html", context)


def delete(request, slug):
    task = Task.objects.get(slug=slug)

    if request.method == "POST":
        task.delete()
        return redirect("/")

    context = {
        "task": task,
    }
    return render(request, "delete.html", context)

tasks/templates/delete.html
<h2>Are you sure to delete {{task.title}} ?</h2>

<a href="{% url 'index:home' %}">Cancel</a>
<br />
<form method="POST">
  {% csrf_token %} {{form}}
  <button type="submit">Confirm</button>
</form>

tasks/templates/list.html
<link
  rel="stylesheet"
  href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
  integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
  crossorigin="anonymous"
/>

<style>
  body {
    background-color: #638cb8;
  }

  input,
  button {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;
  }

  button::placeholder {
    color: #d3d3d3;
  }

  .submit {
    background-color: #6ba3e8;
  }

  .center-column {
    width: 600px;
    margin: 20px auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 3px;
    box-shadow: 6px 2px 30px 0px rgba(0, 0, 0, 0.75);
  }

  .item-row {
    background-color: #906abd;
    margin: 10px;
    padding: 20px;
    border-radius: 3px;
    color: #fff;
    font-size: 16px;
    box-shadow: 0px -1px 10px -4px rgba(0, 0, 0, 0.75);
  }

  .btn-danger {
    background-color: #ffae19;
    border-color: #e59400;
  }
</style>

<div class="center-column">
  <form method="POST" action="/">
    {% csrf_token %} {{form.title}}
    <button class="btn btn-info" type="submit">Add Task</button>
  </form>

  <div class="todo-list">
    {% for task in tasks %}
    <div class="item-row">
      <a class="btn btn-sm btn-info" href="{% url 'index:update' task.slug %}"
        >Update</a
      >
      <a class="btn btn-sm btn-danger" href="{% url 'index:delete' task.slug %}"
        >Delete</a
      >

      {% if task.completed == True %}
      <strike>{{task}}</strike>
      {% else %}
      <span>{{task}}</span>
      {% endif %}
    </div>
    {% endfor %}
  </div>
</div>

tasks/templates/update.html
<h1>Update {{task.title}}...</h1>

<form method="post">
  {% csrf_token %} {{form}}
  <button type="submit">update</button>
</form>